set fenc=utf-8
set nobackup
set noswapfile
set autoread
set hidden
set showcmd
set noerrorbells
set backspace=indent,eol,start

set number
set cursorline
set showmatch
set laststatus=2
syntax enable
set title
"colorscheme desert
set list
set listchars=tab:\ \ ,trail:\ 
highlight SpecialKey ctermbg=235 guibg=#2c2d27
set colorcolumn=120
highlight ColorColumn ctermbg=235 guibg=#2c2d27

set list listchars=tab:\▸\-
set expandtab
set tabstop=2
set shiftwidth=2


set ignorecase
set smartcase
set incsearch
set wrapscan
set hlsearch
nmap <Esc><Esc> :nohlsearch<CR><Esc>
